site_name: CP Playbook
site_description: A competitive programming training resource created for LCPC preparation and broader CP growth, maintained by the SHU Developers Club community.
site_url: https://marwanelamami.github.io/cp-shu-devs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/marwanelamami/cp-shu-devs
repo_name: marwanelamami/cp-shu-devs

nav:
  - Home: index.md
  - "Basics":
    - "Intro to Programming": topics/basics/what-is-programming.md
    - "Learn a Language":
      - "Intro to C++ and Setting up the Environment": topics/basics/intro-to-c-and-setting-up-the-environment.md
      - "Data Types, Variables and Input Output": topics/basics/data-types-variables-and-input-output.md
      - "Operators": topics/basics/operators.md
      - "Conditional Statements": topics/basics/conditional-statements.md
      - "Loops": topics/basics/loops.md
      - "Functions": topics/basics/functions.md
      - "Static Arrays": topics/basics/02-arrays/static-arrays.md
      - "Dynamic Arrays": topics/basics/02-arrays/dynamic-arrays.md
      - "Strings": topics/basics/strings.md
      - "Pointers and References": topics/basics/pointers-and-references.md
      - "Structures": topics/basics/structures.md
    - "Intro to Competitive Programming": topics/basics/01-intro-to-cp/intro-to-cp.md
    - "Bitwise Thinking": topics/basics/bitwise-operations-and-bitmasks.md
    - "Complexity Analysis":
      - "Big O Notation and Time and Space Complexity Analysis": topics/basics/01-intro-to-cp/complexity-analysis.md
      - "Fast Input Output": topics/basics/fast-input-output.md
    - "Recursion": topics/basics/recursion.md
    - "Very Basic Math":
      - "Divisors": topics/basics/divisors.md
      - "GCD and LCM": topics/basics/gcd-and-lcm.md
      - "Harmonic Number": topics/basics/harmonic-number.md
    - "Range Queries Without Updates":
      - "Prefix Sum": topics/basics/06-prefix-sums/prefix-sums.md
      - "Prefix XOR": topics/basics/prefix-xor.md
    - "Standard Template Library (STL)":
      - "Intro to STL, Containers and Iterators": topics/basics/intro-to-stl-containers-and-iterators.md
      - "Pairs and Tuples": topics/basics/pairs-and-tuples.md
      - "Vector": topics/basics/vector.md
      - "Stack": topics/basics/stack.md
      - "Queue": topics/basics/queue.md
      - "Priority Queue / Heap": topics/basics/priority-queue-heap.md
      - "Deque": topics/basics/deque.md
      - "Set, Unordered Set and Multiset": topics/basics/set-unordered-set-and-multiset.md
      - "Map and Unordered Map": topics/basics/map-and-unordered-map.md
      - "Bitset": topics/basics/bitset.md
      - "List / Linked List": topics/basics/list-linked-list.md
    - "Leveraging Monotonicity":
      - "Binary Search": topics/basics/binary-search.md
      - "Two Pointers": topics/basics/05-two-pointers/two-pointers.md
    - "Basic Sorting Algorithms":
      - "Bubble Sort": topics/basics/bubble-sort.md
      - "Selection Sort": topics/basics/selection-sort.md
      - "Insertion Sort": topics/basics/insertion-sort.md
      - "Counting Sort": topics/basics/counting-sort.md
      - "Merge Sort": topics/basics/merge-sort.md
      - "Quick Sort": topics/basics/quick-sort.md
      - "Radix Sort": topics/basics/radix-sort.md
      - "C++ STL Sort and Custom Comparator": topics/basics/c-stl-sort-and-custom-comparator.md
    - "Divide and Conquer": topics/basics/divide-and-conquer.md
    - "Greedy and Constructive":
      - "Basic Greedy Algorithms": topics/basics/basic-greedy-algorithms.md
      - "Basic Constructive Algorithms": topics/basics/basic-constructive-algorithms.md
    - "2D Prefix Sum": topics/basics/2d-prefix-sum.md
    - "More Techniques":
      - "Difference Array": topics/basics/difference-array.md
      - "Sliding Window Technique": topics/basics/04-sliding-window/variable-size.md
    - "Bit Manipulation":
      - "Bit Manipulation": topics/basics/bit-manipulation.md
      - "The XOR Trick": topics/basics/the-xor-trick.md
    - "Basic Modular Arithmetic":
      - "Binary Exponentiation and Basic Modular Arithmetic": topics/basics/binary-exponentiation-and-basic-modular-arithmetic.md
      - "Fermat's Little Theorem and Modular Inverse": topics/basics/fermat-s-little-theorem-and-modular-inverse.md
    - "Basic Counting":
      - "Permutations, Combinations and Basic Counting Problems": topics/basics/permutations-combinations-and-basic-counting-problems.md
      - "Stars and Bars": topics/basics/stars-and-bars.md
      - "Pigeonhole Principle": topics/basics/pigeonhole-principle.md
    - "Very Basic Graphs": topics/basics/introduction-to-graphs-definitions-and-representations.md
  - Useful Links: resources.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - tables
  - attr_list
